### ISSUE TITLE
Add token validation for devices

### ISSUE THREAD

**Issue by joshsmith** [Bernie-2016/fieldthebern-api#99]
```
ActiveRecord::RecordNotUnique: PG::UniqueViolation: ERROR:  duplicate key value violates unique constraint "index_devices_on_token"
DETAIL:  Key (token)=(<null>) already exists.
: INSERT INTO "devices" ("token", "user_id", "created_at", "updated_at") VALUES ($1, $2, $3, $4) RETURNING "id"
```

Devices should never have a `null` token.

**Comment by datapolitical** [comment]
I could be misreading the code, but it looks like we're storing the device token as a string and it should be stored in binary.

http://stackoverflow.com/questions/25680077/device-token-null

**Comment by joshsmith** [comment]
@datapolitical are you sure this is the case? It's working fine generally other than our failure to validate its presence.

**Comment by joshsmith** [comment]
Tested on real devices with push notifications.

**Comment by datapolitical** [comment]
right, and he was having the same problem. 5% of users returning null tokens, and it's because the token is getting stored as a string rather than a binary.

**Comment by joshsmith** [comment]
From what I can tell the token is a `String?` that looks like `4779d4660fa0c97fbbe6146c054e584b2dc2f27d676fe08efb8c7a2a54e9b54c` and is `nil` on emulators, in which case it should not be sent to the server.
